networks:
  dspacenet:
    ipam:
      config:
        - subnet: 172.23.0.0/16
services:
  # Dspace UI
  ui:
     container_name: dspace-ui
     image: fbn/dspace-ui:${DSPACE_VERSION}-dist
     build: 
       context: .
       dockerfile: ./ui-dist.dockerfile
      #  dockerfile: ./ui.dockerfile        
     env_file:
       - .env
     environment:
      - NODE_ENV=production
      - DSPACE_REST_SSL=true
      - DSPACE_REST_HOST=ri.fbnovas.edu.br
      - DSPACE_REST_PORT=443
      - DSPACE_REST_NAMESPACE=/server
     networks:
       - dspacenet
     ports:
     - published: 4000
       target: 4000
     stdin_open: true
     tty: true
     restart: unless-stopped   

  # DSpace (backend) webapp container
  api:
    env_file:
      - .env
    container_name: dspace-api
    environment:
      matomo__P__tracker__P__url: http://matomo
    image: fbn/dspace-api:${DSPACE_VERSION}
    build:
      context: .
      dockerfile: api.dockerfile
    depends_on:
    - dspacedb
    - dspacesolr
    networks:
      - dspacenet
    ports:
    - published: 8080
      target: 8080
    - published: 8000
      target: 8000
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
    # Keep DSpace assetstore directory between reboots
    - assetstore:/dspace/assetstore
    # Mount local [src]/dspace/config/ to container. This syncs your local configs with container
    # NOTE: Environment variables specified above will OVERRIDE any configs in local.cfg or dspace.cfg
    - ./api/dspace/config:/dspace/config
    # Ensure that the database is ready BEFORE starting tomcat
    # 1. While a TCP connection to dspacedb port 5432 is not available, continue to sleep
    # 2. Then, run database migration to init database tables
    # 3. Finally, start DSpace
    entrypoint:
    - /bin/bash
    - '-c'
    - |
      while (!</dev/tcp/dspacedb/5432) > /dev/null 2>&1; do sleep 1; done;
      /dspace/bin/dspace database migrate
      java -jar /dspace/webapps/server-boot.jar --dspace.dir=/dspace
  
  # DSpace PostgreSQL database container
  dspacedb:
    container_name: dspacedb
    # Uses a custom Postgres image with pgcrypto installed
    image: fbn/dspacedb:${DSPACE_VERSION}
    env_file:
      - .env
    build:
      # Must build out of subdirectory to have access to install script for pgcrypto
      context: ./docker/db/
    networks:
      dspacenet:
    ports:
    - published: 5432
      target: 5432
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
    # Keep Postgres data directory between reboots
    - pgdata:/pgdata

  # DSpace Solr container
  dspacesolr:
    container_name: dspacesolr
    image: fbn/dspacesolr:${DSPACE_VERSION}
    env_file:
      - .env
    build:
      context: ./docker/solr/
      # Provide path to Solr configs necessary to build Docker image
      additional_contexts:
        solrconfigs: ./api/dspace/solr
      args:
        SOLR_VERSION:  ${SOLR_VERSION}
    networks:
      dspacenet:
    ports:
    - published: 8983
      target: 8983
    stdin_open: true
    tty: true
    working_dir: /var/solr/data
    volumes:
    # Keep Solr data directory between reboots
    - solr_data:/var/solr/data
    user: root
    restart: unless-stopped
    entrypoint:
    - /bin/bash
    - '-c'
    - |
      init-var-solr
      precreate-core authority /opt/solr/server/solr/configsets/authority
      cp -r /opt/solr/server/solr/configsets/authority/* authority
      precreate-core oai /opt/solr/server/solr/configsets/oai
      cp -r /opt/solr/server/solr/configsets/oai/* oai
      precreate-core search /opt/solr/server/solr/configsets/search
      cp -r /opt/solr/server/solr/configsets/search/* search
      precreate-core statistics /opt/solr/server/solr/configsets/statistics
      cp -r /opt/solr/server/solr/configsets/statistics/* statistics
      precreate-core qaevent /opt/solr/server/solr/configsets/qaevent
      cp -r /opt/solr/server/solr/configsets/qaevent/* qaevent
      precreate-core suggestion /opt/solr/server/solr/configsets/suggestion
      cp -r /opt/solr/server/solr/configsets/suggestion/* suggestion
      chown -R solr:solr /var/solr
      runuser -u solr -- solr-foreground
volumes:
  assetstore:
  pgdata:
  solr_data:
