rest:
  ssl: true
  host: ri.fbnovas.edu.br
  port: 443
  nameSpace: /server
  ssrBaseUrl: https://ri.fbnovas.edu.br/server

themes:
  - name: fbn
    headTags:
    - tagName: title
      attributes:
        content: "RI FBN"
    - tagName: link
      attributes:
        rel: icon
        href: assets/fbn/images/favicon_io/favicon.ico
        sizes: any
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: assets/fbn/images/favicon_io/apple-touch-icon.png
    - tagName: link
      attributes:
        rel: manifest
        href: assets/fbn/images/favicon_io/site.webmanifest

defaultLanguage: pt_BR